const school = {
  id: "550e8400-e29b-41d4-a716-446655440001",
  publicId: "CD-2026-0001",
  code: "CD-2026-0001",
  name: "Universite de Kinshasa",
  type: "Universite",
  city: "Kinshasa",
  country: "RDC",
  address: "Avenue de l'Universite, Kinshasa",
  phone: "+243 810 000 000",
  email: "contact@unikin.schoollink",
  website: "https://unikin.schoollink",
  currency: "CDF",
  slogan: "Excellence et Innovation",
  status: "Actif",
  logoUrl: "",
  schoolYear: "2025-2026",
  timezone: "Africa/Kinshasa",
  language: "Français",
  dateFormat: "JJ-MM-AAAA",
  primaryColor: "#2563EB",
  subscriptionPlan: "Premium",
  subscriptionStartDate: "01-09-2025",
  subscriptionEndDate: "31-08-2026",
  validationStatus: "Validé",
  subscriptionStatus: "À jour",
  maxStudents: 1200,
  maxTeachers: 120,
  createdAt: "01-09-2025",
};

const rolePermissions = {
  "Super Administrateur SchoolLink": [
    "ALL_PRIVILEGES",
    "Contrôler tous les pays",
    "Créer un pays",
    "Modifier un pays",
    "Suspendre un pays",
    "Réactiver un pays",
    "Supprimer un pays",
    "Affecter un administrateur pays",
    "Contrôler tous les établissements",
    "Gérer administrateurs pays",
    "Gérer administrateurs écoles",
    "Gérer abonnements",
    "Modifier tarifs par pays",
    "Gérer utilisateurs",
    "Voir rapports globaux",
    "Auditer connexions",
  ],
  "Admin Pays": [
    "COUNTRY_PRIVILEGES",
    "Gérer établissements du pays",
    "Créer un établissement",
    "Modifier un établissement",
    "Suspendre un établissement",
    "Réactiver un établissement",
    "Valider une inscription",
    "Refuser une inscription",
    "Demander pièces complémentaires",
    "Gérer admins écoles du pays",
    "Voir rapports pays",
    "Suivre abonnements pays",
    "Relancer établissements en retard",
    "Auditer utilisateurs pays",
  ],
  "Admin School": [
    "Voir élèves",
    "Gérer élèves",
    "Gérer enseignants",
    "Gérer classes",
    "Gérer cours",
    "Gérer paiements",
    "Gérer utilisateurs",
    "Gérer annonces",
  ],
  Directeur: ["Voir élèves", "Modifier notes", "Gérer paiements", "Gérer utilisateurs", "Voir rapports"],
  Secrétaire: ["Voir élèves", "Gérer élèves", "Gérer paiements", "Gérer appels"],
  Enseignant: ["Voir élèves", "Modifier notes", "Faire appel", "Messages parents"],
  Parent: ["Voir enfant", "Voir paiements", "Messages école"],
  "Élève / Étudiant": ["Voir notes", "Voir présences", "Voir paiements"],
  Comptable: ["Gérer paiements", "Voir rapports financiers"],
  Surveillant: ["Voir élèves", "Gérer appels", "Gérer discipline"],
};

const countries = [
  {
    id: "COUNTRY-RDC",
    name: "République Démocratique du Congo",
    code: "CD",
    phonePrefix: "+243",
    currency: "CDF",
    timezone: "Africa/Kinshasa",
    status: "Actif",
    administratorId: "USER-COUNTRY-RDC",
    createdAt: "01-09-2025",
  },
  {
    id: "COUNTRY-CG",
    name: "République du Congo",
    code: "CG",
    phonePrefix: "+242",
    currency: "XAF",
    timezone: "Africa/Brazzaville",
    status: "Suspendu",
    administratorId: "",
    createdAt: "15-05-2026",
  },
];

const subscriptions = [
  {
    id: "SUB-CD-2026-0001",
    schoolCode: "CD-2026-0001",
    countryCode: "CD",
    country: "RDC",
    plan: "Premium",
    monthlyPrice: 120,
    annualPrice: 1200,
    currency: "USD",
    status: "Actif",
    paymentStatus: "À jour",
    startDate: "01-09-2025",
    endDate: "31-08-2026",
    lastPaymentDate: "01-06-2026",
  },
  {
    id: "SUB-CG-2026-0001",
    schoolCode: "CG-2026-0001",
    countryCode: "CG",
    country: "République du Congo",
    plan: "Standard",
    monthlyPrice: 80,
    annualPrice: 800,
    currency: "USD",
    status: "Suspendu",
    paymentStatus: "En retard",
    startDate: "01-01-2026",
    endDate: "31-05-2026",
    lastPaymentDate: "01-04-2026",
  },
];

const platformNotifications = [
  {
    id: "NOTIF-001",
    audience: "Super Administrateur SchoolLink",
    countryCode: "*",
    title: "Nouveau pays créé",
    message: "La République du Congo a été ajoutée au périmètre SchoolLink.",
    type: "Pays",
    status: "Non lu",
    date: "01-06-2026",
  },
  {
    id: "NOTIF-002",
    audience: "Super Administrateur SchoolLink",
    countryCode: "*",
    title: "Abonnement expiré",
    message: "Un abonnement pays est arrivé à échéance.",
    type: "Abonnement",
    status: "Non lu",
    date: "01-06-2026",
  },
  {
    id: "NOTIF-003",
    audience: "Admin Pays",
    countryCode: "CD",
    title: "Paiement reçu",
    message: "Université de Kinshasa a réglé son abonnement Premium.",
    type: "Paiement",
    status: "Lu",
    date: "01-06-2026",
  },
  {
    id: "NOTIF-004",
    audience: "Admin Pays",
    countryCode: "CD",
    title: "Nouvelle demande d'inscription",
    message: "Une nouvelle école attend validation dans votre pays.",
    type: "Inscription",
    status: "Non lu",
    date: "02-06-2026",
  },
];

const userAccounts = [
  {
    id: "USER-ADMIN1",
    publicId: "USR-2026-000001",
    lastName: "Administrateur",
    firstName: "SchoolLink",
    gender: "Masculin",
    phone: "+243 810 000 000",
    email: "admin@unikin.schoollink",
    role: "Admin School",
    secondaryRoles: [],
    scopeLevel: "Établissement",
    countryScope: "RDC",
    schoolCode: "CD-2026-0001",
    accessChannel: "Application",
    identifier: "admin",
    status: "Actif",
    permissions: rolePermissions["Admin School"],
    temporaryPassword: "",
    photoUrl: "",
    createdAt: "01-09-2025",
    lastLoginAt: "01-06-2026",
    createdBy: "Super Administrateur SchoolLink",
    history: ["Compte initial créé le 01-09-2025"],
  },
  {
    id: "USER-SUPERADMIN",
    publicId: "USR-2026-000002",
    lastName: "SchoolLink",
    firstName: "Super Admin",
    gender: "Masculin",
    phone: "+243 810 000 900",
    email: "superadmin@schoollink.app",
    role: "Super Administrateur SchoolLink",
    secondaryRoles: [],
    scopeLevel: "Global",
    countryScope: "",
    schoolCode: "*",
    accessChannel: "BackOffice",
    identifier: "superadmin",
    password: "1234",
    status: "Actif",
    permissions: rolePermissions["Super Administrateur SchoolLink"],
    temporaryPassword: "",
    photoUrl: "",
    createdAt: "01-09-2025",
    lastLoginAt: "01-06-2026",
    createdBy: "Système",
    history: ["Compte global créé le 01-09-2025"],
  },
  {
    id: "USER-COUNTRY-RDC",
    publicId: "ADM-CD-2026-0001",
    lastName: "Admin",
    firstName: "RDC",
    gender: "Masculin",
    phone: "+243 810 000 901",
    email: "admin.rdc@schoollink.app",
    role: "Admin Pays",
    secondaryRoles: [],
    scopeLevel: "Pays",
    countryScope: "RDC",
    schoolCode: "*",
    accessChannel: "BackOffice",
    identifier: "admin-rdc",
    password: "1234",
    status: "Actif",
    permissions: rolePermissions["Admin Pays"],
    temporaryPassword: "",
    photoUrl: "",
    createdAt: "01-09-2025",
    lastLoginAt: "01-06-2026",
    createdBy: "Super Administrateur SchoolLink",
    history: ["Compte admin pays RDC créé le 01-09-2025"],
  },
  {
    id: "USER-T1",
    publicId: "USR-2026-000004",
    lastName: "Kabeya",
    firstName: "Jean",
    gender: "Masculin",
    phone: "+243 810 000 101",
    email: "jean.kabeya@schoollink.cd",
    role: "Enseignant",
    secondaryRoles: [],
    scopeLevel: "Établissement",
    countryScope: "RDC",
    schoolCode: "CD-2026-0001",
    accessChannel: "Application",
    identifier: "T1",
    status: "Actif",
    permissions: rolePermissions.Enseignant,
    temporaryPassword: "",
    photoUrl: "",
    createdAt: "01-09-2025",
    lastLoginAt: "31-05-2026",
    createdBy: "Administrateur",
    history: ["Compte enseignant créé le 01-09-2025"],
  },
  {
    id: "USER-PARENT1",
    publicId: "USR-2026-000005",
    lastName: "Dupont",
    firstName: "Parent",
    gender: "Masculin",
    phone: "+243 820 000 001",
    email: "parent.dupont@example.com",
    role: "Parent",
    secondaryRoles: [],
    scopeLevel: "Établissement",
    countryScope: "RDC",
    schoolCode: "CD-2026-0001",
    accessChannel: "Application",
    identifier: "+243 820 000 001",
    status: "Actif",
    permissions: rolePermissions.Parent,
    temporaryPassword: "",
    photoUrl: "",
    createdAt: "01-09-2025",
    lastLoginAt: "31-05-2026",
    createdBy: "Administrateur",
    history: ["Compte parent créé le 01-09-2025"],
  },
];

const teachers = [
  {
    id: "T1",
    publicId: "CD-2026-0001-ENS-0001",
    name: "Jean Kabeya",
    firstName: "Jean",
    gender: "Masculin",
    phone: "+243 810 000 101",
    email: "jean.kabeya@schoollink.cd",
    mainSubject: "Mathematiques",
    password: "1234",
    assignments: [
      { className: "6ème A", course: "Mathématiques" },
      { className: "6ème B", course: "Mathématiques" },
      { className: "5ème A", course: "Physique" },
    ],
  },
  {
    id: "T2",
    publicId: "CD-2026-0001-ENS-0002",
    name: "Marie Mukendi",
    firstName: "Marie",
    gender: "Féminin",
    phone: "+243 810 000 102",
    email: "marie.mukendi@schoollink.cd",
    mainSubject: "Francais",
    password: "1234",
    assignments: [
      { className: "6ème A", course: "Français" },
      { className: "5ème B", course: "Français" },
    ],
  },
  {
    id: "T3",
    publicId: "CD-2026-0001-ENS-0003",
    name: "Patrick Ilunga",
    firstName: "Patrick",
    gender: "Masculin",
    phone: "+243 810 000 103",
    email: "patrick.ilunga@schoollink.cd",
    mainSubject: "Sciences",
    password: "1234",
    assignments: [
      { className: "6ème B", course: "Sciences" },
      { className: "5ème A", course: "Sciences" },
    ],
  },
  {
    id: "T4",
    publicId: "CD-2026-0001-ENS-0004",
    name: "Sarah Mbuyi",
    firstName: "Sarah",
    gender: "Féminin",
    phone: "+243 810 000 104",
    email: "sarah.mbuyi@schoollink.cd",
    mainSubject: "Histoire",
    password: "1234",
    assignments: [
      { className: "5ème A", course: "Histoire" },
      { className: "5ème B", course: "Histoire" },
    ],
  },
];

const classes = [
  { id: "C1", publicId: "CLS-2026-000001", name: "6ème A", level: "6ème", track: "Generale", teacherId: "T1" },
  { id: "C2", publicId: "CLS-2026-000002", name: "6ème B", level: "6ème", track: "Generale", teacherId: "T2" },
  { id: "C3", publicId: "CLS-2026-000003", name: "5ème A", level: "5ème", track: "Sciences", teacherId: "T3" },
  { id: "C4", publicId: "CLS-2026-000004", name: "5ème B", level: "5ème", track: "Lettres", teacherId: "T4" },
];

const courses = [
  { id: "COURSE1", publicId: "COU-2026-000001", className: "6ème A", name: "Mathématiques", coefficient: 2 },
  { id: "COURSE2", publicId: "COU-2026-000002", className: "6ème A", name: "Français", coefficient: 1 },
  { id: "COURSE3", publicId: "COU-2026-000003", className: "6ème B", name: "Mathématiques", coefficient: 2 },
  { id: "COURSE4", publicId: "COU-2026-000004", className: "6ème B", name: "Sciences", coefficient: 2 },
  { id: "COURSE5", publicId: "COU-2026-000005", className: "5ème A", name: "Physique", coefficient: 2 },
  { id: "COURSE6", publicId: "COU-2026-000006", className: "5ème A", name: "Histoire", coefficient: 1 },
  { id: "COURSE7", publicId: "COU-2026-000007", className: "5ème B", name: "Français", coefficient: 1 },
  { id: "COURSE8", publicId: "COU-2026-000008", className: "5ème B", name: "Histoire", coefficient: 1 },
];

const students = [
  { id: "1", publicId: "CD-2026-0001-ELE-0001", name: "Jean Dupont", firstName: "Jean", matricule: "CD-2026-0001-ELE-0001", gender: "Masculin", birthDate: "12-04-2012", className: "6ème A", schoolCode: "CD-2026-0001", pin: "1234", parentName: "Parent Dupont", parentPhone: "+243 820 000 001", parentEmail: "parent.dupont@example.com", archived: false },
  { id: "2", publicId: "CD-2026-0001-ELE-0002", name: "Marie Martin", firstName: "Marie", matricule: "CD-2026-0001-ELE-0002", gender: "Féminin", birthDate: "18-09-2012", className: "6ème A", schoolCode: "CD-2026-0001", pin: "1234", parentName: "Parent Martin", parentPhone: "+243 820 000 001", parentEmail: "parent.martin@example.com", archived: false },
  { id: "3", publicId: "CD-2026-0001-ELE-0003", name: "Paul Bernard", firstName: "Paul", matricule: "CD-2026-0001-ELE-0003", gender: "Masculin", birthDate: "03-02-2011", className: "6ème B", schoolCode: "CD-2026-0001", pin: "1234", parentName: "Parent Bernard", parentPhone: "+243 820 000 003", parentEmail: "parent.bernard@example.com", archived: false },
  { id: "4", publicId: "CD-2026-0001-ELE-0004", name: "Sarah Mbala", firstName: "Sarah", matricule: "CD-2026-0001-ELE-0004", gender: "Féminin", birthDate: "21-07-2011", className: "5ème A", schoolCode: "CD-2026-0001", pin: "1234", parentName: "Parent Mbala", parentPhone: "+243 820 000 004", parentEmail: "parent.mbala@example.com", archived: false },
];

const notes = [
  { id: "N1", studentId: "1", subject: "Mathématiques", value: 15, coefficient: 2, date: "2026-05-20" },
  { id: "N2", studentId: "1", subject: "Français", value: 13, coefficient: 1, date: "2026-05-22" },
  { id: "N3", studentId: "2", subject: "Mathématiques", value: 16, coefficient: 2, date: "2026-05-21" },
  { id: "N4", studentId: "3", subject: "Sciences", value: 12, coefficient: 2, date: "2026-05-23" },
];

const presences = [
  { id: "P1", publicId: "PRE-2026-000001", studentId: "1", date: "2026-05-27", present: true, status: "Present" },
  { id: "P2", publicId: "PRE-2026-000002", studentId: "1", date: "2026-05-28", present: false, status: "Absent" },
  { id: "P3", publicId: "PRE-2026-000003", studentId: "2", date: "2026-05-27", present: true, status: "Present" },
  { id: "P4", publicId: "PRE-2026-000004", studentId: "3", date: "2026-05-27", present: true, status: "Retard" },
];

const payments = [
  { id: "PAY1", publicId: "PAY-2026-000001", studentId: "1", amount: 25000, date: "2026-05-10", status: "PAYE", method: "Mobile Money" },
  { id: "PAY2", publicId: "PAY-2026-000002", studentId: "1", amount: 15000, date: "2026-05-25", status: "EN_ATTENTE", method: "Especes" },
  { id: "PAY3", publicId: "PAY-2026-000003", studentId: "2", amount: 25000, date: "2026-05-10", status: "PAYE", method: "Virement bancaire" },
  { id: "PAY4", publicId: "PAY-2026-000004", studentId: "3", amount: 25000, date: "2026-05-12", status: "PAYE", method: "Carte bancaire" },
];

const announcements = [
  { id: "A1", title: "Reunion des parents", message: "Reunion generale samedi a 10h00.", date: "2026-05-30" },
  { id: "A2", title: "Examens", message: "Les evaluations commencent le 10 juin.", date: "2026-05-29" },
];

module.exports = {
  school,
  teachers,
  classes,
  courses,
  students,
  notes,
  presences,
  payments,
  announcements,
  rolePermissions,
  userAccounts,
  countries,
  subscriptions,
  platformNotifications,
};
